name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  behat:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

#      - name: Run a one-line script
#        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          php --version
          composer --version
          mysql --version
