name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  behat:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

#      - name: Run a one-line script
#        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          composer install
          php -S 0.0.0.0:8080 -t www vendor/phpgt/webengine/go.php &
          vendor/bin/behat -c test/behat/behat.yml
          killall php
